# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoFTP_small.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 636)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 9, 341, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.list_input = QtWidgets.QListView(self.tab)
        self.list_input.setGeometry(QtCore.QRect(20, 30, 291, 101))
        self.list_input.setDragEnabled(True)
        self.list_input.setObjectName("list_input")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, -4, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(17, 160, 301, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_start = QtWidgets.QPushButton(self.tab)
        self.btn_start.setGeometry(QtCore.QRect(20, 310, 291, 61))
        self.btn_start.setObjectName("btn_start")
        self.btn_pause = QtWidgets.QPushButton(self.tab)
        self.btn_pause.setGeometry(QtCore.QRect(20, 370, 291, 41))
        self.btn_pause.setObjectName("btn_pause")
        self.line_currentfile = QtWidgets.QLineEdit(self.tab)
        self.line_currentfile.setGeometry(QtCore.QRect(20, 490, 291, 21))
        self.line_currentfile.setObjectName("line_currentfile")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(27, 520, 281, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(20, 400, 291, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 420, 311, 64))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_ohost_current = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_ohost_current.setFont(font)
        self.lbl_ohost_current.setObjectName("lbl_ohost_current")
        self.gridLayout.addWidget(self.lbl_ohost_current, 1, 1, 1, 1)
        self.lbl_ohost = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_ohost.setFont(font)
        self.lbl_ohost.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_ohost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_ohost.setObjectName("lbl_ohost")
        self.gridLayout.addWidget(self.lbl_ohost, 1, 0, 1, 1)
        self.lbl_thost_current = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_thost_current.setFont(font)
        self.lbl_thost_current.setObjectName("lbl_thost_current")
        self.gridLayout.addWidget(self.lbl_thost_current, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.lbl_thost = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_thost.setFont(font)
        self.lbl_thost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_thost.setObjectName("lbl_thost")
        self.gridLayout.addWidget(self.lbl_thost, 2, 0, 1, 1)
        self.lbl_ohost_status = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_ohost_status.setFont(font)
        self.lbl_ohost_status.setObjectName("lbl_ohost_status")
        self.gridLayout.addWidget(self.lbl_ohost_status, 1, 2, 1, 1)
        self.lbl_thost_status = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_thost_status.setFont(font)
        self.lbl_thost_status.setObjectName("lbl_thost_status")
        self.gridLayout.addWidget(self.lbl_thost_status, 2, 2, 1, 1)
        self.combo_ohost = QtWidgets.QComboBox(self.tab)
        self.combo_ohost.setGeometry(QtCore.QRect(20, 205, 171, 21))
        self.combo_ohost.setObjectName("combo_ohost")
        self.combo_ohost.addItem("")
        self.combo_ohost.addItem("")
        self.combo_ohost.addItem("")
        self.combo_ohost.addItem("")
        self.combo_ohost.addItem("")
        self.combo_thost = QtWidgets.QComboBox(self.tab)
        self.combo_thost.setGeometry(QtCore.QRect(20, 245, 171, 21))
        self.combo_thost.setObjectName("combo_thost")
        self.combo_thost.addItem("")
        self.combo_thost.addItem("")
        self.combo_thost.addItem("")
        self.combo_thost.addItem("")
        self.combo_thost.addItem("")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 221, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 260, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(29, 280, 271, 21))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rad_binary = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.rad_binary.setObjectName("rad_binary")
        self.gridLayout_2.addWidget(self.rad_binary, 0, 1, 1, 1)
        self.rad_auto = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.rad_auto.setObjectName("rad_auto")
        self.gridLayout_2.addWidget(self.rad_auto, 0, 0, 1, 1)
        self.rad_other = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.rad_other.setObjectName("rad_other")
        self.gridLayout_2.addWidget(self.rad_other, 0, 2, 1, 1)
        self.btn_connect = QtWidgets.QPushButton(self.tab)
        self.btn_connect.setGeometry(QtCore.QRect(200, 210, 111, 61))
        self.btn_connect.setObjectName("btn_connect")
        self.btn_autoFetchEmails = QtWidgets.QPushButton(self.tab)
        self.btn_autoFetchEmails.setGeometry(QtCore.QRect(210, 131, 101, 41))
        self.btn_autoFetchEmails.setObjectName("btn_autoFetchEmails")
        self.btn_add = QtWidgets.QPushButton(self.tab)
        self.btn_add.setGeometry(QtCore.QRect(160, 131, 51, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listView_2 = QtWidgets.QListView(self.tab_2)
        self.listView_2.setGeometry(QtCore.QRect(10, 20, 311, 201))
        self.listView_2.setObjectName("listView_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listView_3 = QtWidgets.QListView(self.tab_2)
        self.listView_3.setGeometry(QtCore.QRect(10, 250, 311, 241))
        self.listView_3.setObjectName("listView_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(12, 500, 301, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 22))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFIle.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "autoFTP"))
        self.label.setText(_translate("MainWindow", "Input Pipeline"))
        self.label_2.setText(_translate("MainWindow", "Transfer Options"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_pause.setText(_translate("MainWindow", "Reset"))
        self.lbl_ohost_current.setText(_translate("MainWindow", "[CURRENT HOST]"))
        self.lbl_ohost.setText(_translate("MainWindow", "   Host Origin:"))
        self.lbl_thost_current.setText(_translate("MainWindow", "[TARGET HOST]"))
        self.label_5.setText(_translate("MainWindow", "Progress"))
        self.lbl_thost.setText(_translate("MainWindow", "   Host Target:"))
        self.lbl_ohost_status.setText(_translate("MainWindow", "STATUS"))
        self.lbl_thost_status.setText(_translate("MainWindow", "STATUS"))
        self.combo_ohost.setItemText(0, _translate("MainWindow", "Automatic"))
        self.combo_ohost.setItemText(1, _translate("MainWindow", "Local"))
        self.combo_ohost.setItemText(2, _translate("MainWindow", "Bronze"))
        self.combo_ohost.setItemText(3, _translate("MainWindow", "Silver"))
        self.combo_ohost.setItemText(4, _translate("MainWindow", "Production"))
        self.combo_thost.setItemText(0, _translate("MainWindow", "Automatic"))
        self.combo_thost.setItemText(1, _translate("MainWindow", "Local"))
        self.combo_thost.setItemText(2, _translate("MainWindow", "Bronze"))
        self.combo_thost.setItemText(3, _translate("MainWindow", "Silver"))
        self.combo_thost.setItemText(4, _translate("MainWindow", "Production"))
        self.label_6.setText(_translate("MainWindow", "Host Origin"))
        self.label_7.setText(_translate("MainWindow", "Host Target"))
        self.label_8.setText(_translate("MainWindow", "Transfer Mode"))
        self.rad_binary.setText(_translate("MainWindow", "Binary"))
        self.rad_auto.setText(_translate("MainWindow", "Auto"))
        self.rad_other.setText(_translate("MainWindow", "Other"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.btn_autoFetchEmails.setText(_translate("MainWindow", "Auto Fetch"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_3.setText(_translate("MainWindow", "Successful Files"))
        self.label_4.setText(_translate("MainWindow", "Failed Files"))
        self.pushButton_3.setText(_translate("MainWindow", "View Full Logs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

